# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BankAccount' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BankAccount

 pod 'Alamofire'
 pod 'ObjectMapper'

  target 'BankAccountTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BankAccountUITests' do
    # Pods for testing
  end

end
