# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SlideMenu' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SlideMenu

#  pod 'SDWebImage'
  pod 'Alamofire'
  pod 'ObjectMapper'
  pod 'SDWebImageSwiftUI'
  pod 'SDWebImageWebPCoder'
  pod 'SDWebImageSVGCoder'
  pod 'SDWebImagePDFCoder'

  target 'SlideMenuTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SlideMenuUITests' do
    # Pods for testing
  end

end
